version: '3'

services:
  ci-build:
    image: microsoft/dotnet:2.2.0-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./CustomerApi.sln && dotnet publish ./CustomerApi.sln -c Release -o ./obj/Docker/publish"
