/* 
 * Sample API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;


namespace Common.ViewModels
{
    /// <summary>
    /// Status
    /// </summary>
    [DataContract]
    public partial class Status
    {
        
        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name="code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Narrative
        /// </summary>
        [DataMember(Name="narrative")]
        public string Narrative { get; set; }

    }

}
