/* 
 * Sample API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;


namespace Common.ViewModels
{
    /// <summary>
    /// UserStory
    /// </summary>
    [DataContract]
    public partial class UserStory
    {
        
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets EffortEstimate
        /// </summary>
        [DataMember(Name="effortEstimate")]
        public int EffortEstimate { get; set; }

        /// <summary>
        /// Gets or Sets EffortRemaining
        /// </summary>
        [DataMember(Name="effortRemaining")]
        public int EffortRemaining { get; set; }

        /// <summary>
        /// Gets or Sets EffortLogged
        /// </summary>
        [DataMember(Name="effortLogged")]
        public int EffortLogged { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status")]
        public Status Status { get; set; }

    }

}
