/* 
 * Sample API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Common.ViewModels
{
    /// <summary>
    /// UserStoryModel
    /// </summary>
    [DataContract]
    public partial class UserStoryModel
    {
        /// <summary>
        /// Gets or Sets UserStory
        /// </summary>
        [DataMember(Name="userStory")]
        public List<UserStory> UserStory { get; set; }

        /// <summary>
        /// Gets or Sets Paging
        /// </summary>
        [DataMember(Name="paging")]
        public Paging Paging { get; set; }

    }

}
