/* 
 * Sample API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CodeAndNarrative
    /// </summary>
    [DataContract]
    public partial class CodeAndNarrative :  IEquatable<CodeAndNarrative>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CodeAndNarrative" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CodeAndNarrative() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CodeAndNarrative" /> class.
        /// </summary>
        /// <param name="code">code (required).</param>
        /// <param name="narrative">narrative (required).</param>
        public CodeAndNarrative(string code = default(string), string narrative = default(string))
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new InvalidDataException("code is a required property for CodeAndNarrative and cannot be null");
            }
            else
            {
                this.Code = code;
            }

            // to ensure "narrative" is required (not null)
            if (narrative == null)
            {
                throw new InvalidDataException("narrative is a required property for CodeAndNarrative and cannot be null");
            }
            else
            {
                this.Narrative = narrative;
            }

        }
        
        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Narrative
        /// </summary>
        [DataMember(Name="narrative", EmitDefaultValue=false)]
        public string Narrative { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CodeAndNarrative {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Narrative: ").Append(Narrative).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CodeAndNarrative);
        }

        /// <summary>
        /// Returns true if CodeAndNarrative instances are equal
        /// </summary>
        /// <param name="input">Instance of CodeAndNarrative to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CodeAndNarrative input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Narrative == input.Narrative ||
                    (this.Narrative != null &&
                    this.Narrative.Equals(input.Narrative))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Narrative != null)
                    hashCode = hashCode * 59 + this.Narrative.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
